apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd       #ArgoCD controller stays here
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: cert-manager
    targetRevision: v1.13.1
    helm:
      values: |
        installCRDs: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager         #Pods will be deployed here
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true